spring.application.name=proyectoasignaciones

# Conexion a SQLite
spring.datasource.url=jdbc:sqlite:proyecto.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
